### ISSUE TITLE
Initiating Github pages for documentation

### ISSUE THREAD

**Issue by as3mbus** [as3mbus/Dialogue-and-Story-Unity#1]
need help initiating github pages from /docs directory
trouble with submodule on initiation

**Comment by rgee0** [comment]
Have you changed the repo settings to look at `master branch docs folder`?

I got a `Hello World` working at https://github.com/rgee0/Test but used `README.md` instead of `index.html` in the `docs` folder

**Comment by as3mbus** [comment]
yeah i did. but it faild on build and look like this
![image](https://user-images.githubusercontent.com/16043293/31576322-9a7848b0-b122-11e7-8d42-42963665cd4a.png)

**Comment by as3mbus** [comment]
ok it now fixed by removing and adding new the module  that cause the error
thx for your help.
if you hav time please look around and inspect my code in case it hav many error
