### ISSUE TITLE
Versioning Older version

### ISSUE THREAD

**Issue by as3mbus** [as3mbus/Dialogue-and-Story-Unity#2]
How to manage git when you have older version that still need to be fixed since it is still used in some case.
So i was wondering how i should manage my git when there are older version that still need several fixing but i also working on newer version which is already reworked on many component. the fix will or wont be present in newer version. 
my current work around is creating branch for this older version fix.
 is there any better way to do this  ?

**Comment by GracesGames** [comment]
A branch is the perfect solution for this. Might want to give the branch the name of the release (major.minor.path) e.g. branch 1.1.0 for version 1.1.0 and start working on master for version 1.1.1 or 1.2.0 :)

**Comment by as3mbus** [comment]
answered and pretty satisfied with it thank you
